### ISSUE TITLE
NodeUp: v0.11 Update Show

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#10]
### [NodeUp #50](http://nodeup.com/fifty)

With:
- @dshaw
- @isaacs
- @piscisaureus
- @bnoordhuis
- @trevnorris
- @tjfontaine

Topics:
- v0.11 breaking changes
- Stream3
- http refactor
- buffers improvements

**Comment by juliangruber** [comment]
@rvagg could be of interest, because https://github.com/rvagg/nan and leveldown and buffers etc.

**Comment by dshaw** [comment]
@juliangruber Out of scope for this show I think, but having @rvagg on with @tjfontaine to discuss compatibility layers would be really interesting. Four is a good number and we're already there. (I added myself to make that more clear.)

Want to create a new issue for that to kick off the discussion?

**Comment by juliangruber** [comment]
did just that :) #11
