### ISSUE TITLE
NodeUp: Compatibility Layer Show

### ISSUE THREAD

**Issue by juliangruber** [nodeup/contribute#11]
### [NodeUp #52](http://nodeup.com/fiftytwo)

With:
- @dshaw
- @tjfontaine
- @rvagg
- @trevnorris

Topics:
- Stories, backgrounds and best practices around maintaining module compatibility across multiple node version that broke backwards compatibility. Binary add-ons could be the focus, but also doing js-land would be even more valuable.
- [tjfontaine/node-addon-layer](https://github.com/tjfontaine/node-addon-layer)
- [rvagg/nan](https://github.com/rvagg/nan)

**Comment by mikeal** [comment]
good idea.

**Comment by dshaw** [comment]
Thanks, @juliangruber.

**Comment by dshaw** [comment]
Per @tootallnate's suggestion, adding @trevnorris.
https://twitter.com/TooTallNate/status/368160057986269187

@trevnorris, does it make sense to have you on this show?

**Comment by dshaw** [comment]
I'm thinking about doing this show next Tuesday 9/3 10:00-11:30 AM PT.

/cc @floating @tjfontaine @rvagg @trevnorris

**Comment by mikeal** [comment]
that could work for me if it was just a little bit later. i can try to be in my office by 10am but it is rather difficult.

**Comment by trevnorris** [comment]
@dshaw Only if you want me to explain some of the breakages I introduced. Though most are very minor and I'd doubt the community would ever notice (e.g. introduced externalized strings, which means you could technically mutate your string in native land w/o JS ever noticing, yeah, that would be something to debug). But as far as compatibility later, my tool isn't. It's just a small set of things I find myself using quite often in my own modules.

**Comment by rvagg** [comment]
I'm not sure I _should_ do this, it's 3am for me: http://www.timeanddate.com/worldclock/converted.html?iso=20130903T10&p1=137&p2=240 and I have a _very_ long flight the next day and I can't usually sleep on planes.

**Comment by dshaw** [comment]
OK, let's push. @rvag, when's the next time you'd be available?

**Comment by rvagg** [comment]
Well, I'm not too busy after my flight and before NodeConf.eu and I'll be in IE so perhaps the timezone matches up better over there?
Or we could even do something live at NodeCon.eu!

**Comment by rvagg** [comment]
@tjfontaine are you going to be in IE perchance? I know @trevnorris will be.

**Comment by tjfontaine** [comment]
@rvagg yes, I'll be there

**Comment by dshaw** [comment]
@tjfontaine Oh, sweet!

**Comment by indexzero** [comment]
Oh man. Do I have some horror stories about `daemon.node`. Turns out `node@0.4.x` was only fork safe "by accident", so forever basically never worked 100% on `0.6.x` and it wasn't until @Avianflu implemented 

```
require('child_process').spawn(/* stuff */, {
  detached: true // <-- this gem
});
```

that we actually had same pure-node.js based daemonization (screw you spellcheck it's a word!).

**Comment by mikeal** [comment]
did this show happen?

**Comment by tjfontaine** [comment]
It did, last week nodeup 52

**Comment by dshaw** [comment]
@mikeal Yes. We focused on NAN and node-addon-layer and the upcoming changes to core rather than on userland as much.

I'd like to get you and @indexzero on for a Maintaining Node Modules horror show. Seems like a better fit.
