### ISSUE TITLE
NodeUp Teams: Groupon

### ISSUE THREAD

**Issue by LauraRoman** [nodeup/contribute#19]
### [NodeUp #58](http://nodeup.com/fiftyeight)

With:
- @dshaw
- @EndangeredMassa 
- @mcculloughsean 
- Adam Geitgey
- @LauraRoman 

Topics:
- Moving Groupon from Rails to Node.js
- I-Tier: Dismantling the Monoliths

**Comment by dshaw** [comment]
@LauraRoman Would love to have the Groupon team on the show. Who would join you?

**Comment by LauraRoman** [comment]
Sri Viswanath, SVP of Engineering and Operations; Sean McCullough, Software Engineer and major driver of move to Node.js; Greg Conklin, Director of Engineering and principal behind I-Tier; Adam Geitgey, Software Engineer and major driver of move to Node.js in partnership with Sean McCullough.

Please see our Groupon Engineering blog.

What date did you have in mind to make the recording?

**Comment by dshaw** [comment]
@LauraRoman Just fleshing out the show at this point. Need to pair down to max 4 participants. Recording gets flakey at > 5 on a panel. Getting everybody else's GitHub handles here would be great. At this point, I'm trying to figure out if this should be a **NodeUp Teams: Groupon** show or something else.

I have a baseline familiarity with the I-Tier project. I've seen the blog posts and The Node Firm helped vet talks for Node Summit. I'm looking forward to meeting Sean at Node Summit and any other team members that are coming. Will you be joining us?

**Comment by LauraRoman** [comment]
Hi Daniel,

Yes, I will be at Node Summit. Will we be recording there? Let's jump on a quick call Monday and work out details. What times work for you to connect by phone?

Laura

**Comment by LauraRoman** [comment]
Hi Daniel,

Following up to this note - how much time would we need to record the
podcast?  Would like to aim for us all meeting and recording 10:30-11am on
Tuesday, Dec. 3.

What do we need to do to prepare for the recording?

Thanks,

Laura

On Sat, Nov 16, 2013 at 11:31 PM, Daniel Shaw notifications@github.comwrote:

> @LauraRoman https://github.com/LauraRoman Just fleshing out the show at
> this point. Need to pair down to max 4 participants. Recording gets flakey
> at > 5 on a panel. Getting everybody else's GitHub handles here would be
> great. At this point, I'm trying to figure out if this should be a _NodeUp
> Teams: Groupon_ show or something else.
> 
> I have a baseline familiarity with the I-Tier project. I've seen the blog
> posts and The Node Firm helped vet talks for Node Summit. I'm looking
> forward to meeting Sean at Node Summit and any other team members that are
> coming. Will you be joining us?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/19#issuecomment-28644211
> .

## 

_Laura Roman_
Head of Technology Public Relations
_GROUPON_
W: 415-814-4261
lroman@groupon.com

**Comment by dshaw** [comment]
Potential dates for this show are 1/2/14 or 1/16/14. I have #21 pencilled in for 1/2 since I imagine being that close to the holidays will be challenging for a teams show. /cc @LauraRoman @mcculloughsean

**Comment by mcculloughsean** [comment]
1/16 works well for me. @jkrems @endangeredmassa @ageitgey @todoubled

**Comment by LauraRoman** [comment]
Daniel,

Let's sync up so I'm clear on how we can best prep, etc.  What are some
good times for to talk later in person tomorrow at Node Summit?

Thx,

Laura

On Mon, Dec 2, 2013 at 9:56 AM, Sean McCullough notifications@github.comwrote:

> 1/16 works well for me. @jkrems https://github.com/jkrems
> @endangeredmassa https://github.com/endangeredmassa @ageitgeyhttps://github.com/ageitgey
> @todoubled https://github.com/todoubled
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/19#issuecomment-29640965
> .

## 

_Laura Roman_
Head of Technology Public Relations
_GROUPON_
W: 415-814-4261
lroman@groupon.com

**Comment by EndangeredMassa** [comment]
I can do either date.

**Comment by EndangeredMassa** [comment]
@dshaw Is this confirmed for 1/16/2014?

How long do the recordings typically take? Do we need to do anything specific to prepare?

**Comment by dshaw** [comment]
Works for me. @ffloating, you good?

Let's shoot for 11am PT. We usually run 60-90 minutes. We'll kick off a
show notes doc as soon as we have final confirmation. Bring your stories!

## 

Daniel Shaw
@dshaw

**Comment by LauraRoman** [comment]
Daniel,

Can you give us some past examples  / working questions, etc.? We need to
have the questions in advance.

How will the recording work?

Thx,

Laura

On Mon, Jan 6, 2014 at 1:03 PM, Daniel Shaw notifications@github.comwrote:

> Works for me. @ffloating, you good?
> 
> Let's shoot for 11am PT. We usually run 60-90 minutes. We'll kick off a
> show notes doc as soon as we have final confirmation. Bring your stories!
> 
> ## 
> 
> Daniel Shaw
> @dshaw
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/19#issuecomment-31686707
> .

## 

_Laura Roman_
Head of Technology Public Relations
_GROUPON_
W: 415-814-4261
lroman@groupon.com

**Comment by dshaw** [comment]
Here are some sample NodeUp Teams shows:
- NodeUp Teams: Trello - http://nodeup.com/fiftyfour 
- NodeUp Teams: DIY.org - http://nodeup.com/fortynine
- NodeUp Teams: Walmart - http://nodeup.com/fiftysix - [transcription](https://github.com/noahcollins/transcriptions/blob/56-a-team-walmart-show-nodebf/56-a-team-walmart-show-nodebf.md)
  - Though this was a bit more about #nodebf than a pure "NodeUp Teams" show. 

We'll kick off a shared doc as soon as we have final confirmation where we'll pencil out the flow of the show. #9 and #23 have typical discussion points. Please feel free to suggest anything else you'd like to discuss.

**Comment by floating** [comment]
@dshaw the 16th works for me

**Comment by LauraRoman** [comment]
Daniel,

We would like to focus on the questions below. Would you please in turn
clarify how the recording will work, logistics, etc.?

Thanks,

Laura

What is [Groupon] for those who may not know?
What parts are served by Node?
What version of Node in prod?
What modules do you use?
How do you use the cluster module? Do you oversubscribe your CPUs?
Describe your tech stack.
Do you use promises?
Do you use CoffeeScript?
Do you use a style guide?
What testing framework do you use?
What was your stack before Node.js?
What dev env tools do you really like?
What about Node.js makes your life easier? Conventions, tools, whatever.

On Mon, Jan 6, 2014 at 1:29 PM, Daniel Shaw notifications@github.comwrote:

> Here are some sample NodeUp Teams shows:
> - NodeUp Teams: Trello - http://nodeup.com/fiftyfour
> - NodeUp Teams: DIY.org - http://nodeup.com/fortynine
> - NodeUp Teams: Walmart - http://nodeup.com/fiftysix - transcriptionhttps://github.com/noahcollins/transcriptions/blob/56-a-team-walmart-show-nodebf/56-a-team-walmart-show-nodebf.md
>   - Though this was a bit more about #nodebf than a pure "NodeUp
>     Teams" show.
> 
> We'll kick off a shared doc as soon as we have final confirmation where
> we'll pencil out the flow of the show. #9https://github.com/nodeup/contribute/issues/9and
> #23 https://github.com/nodeup/contribute/issues/23 have typical
> discussion points. Please feel free to suggest anything else you'd like to
> discuss.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/19#issuecomment-31689079
> .

## 

_Laura Roman_
Head of Technology Public Relations
_GROUPON_
W: 415-814-4261
lroman@groupon.com

**Comment by floating** [comment]
@LauraRoman Hey Laura, I emailed you to get some info and clear up some questions. Email me back when you can at nodeup@gmail.com. Thanks!

**Comment by LauraRoman** [comment]
Hey, will forward info when the team gets back to me with it.

**Comment by dshaw** [comment]
Thank you all for contributing to a great show. :heart_decoration:
