### ISSUE TITLE
NodeUp: A continuation-local-storage Show

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#20]
### [NodeUp #61](http://nodeup.com/sixtyone)

Alternate title: "NodeUp: An AsyncListener Show"

With:
- @dshaw
- @othiym23‎
- @trevnorris 
- @dazld
- @FredKSchott

Topics:
- continuation-local-storage all the things!
  - Why Forrest, why?
  - and how?
  - What now?
  - https://github.com/joyent/node/issues/5243
  - https://github.com/othiym23/node-continuation-local-storage
  - http://fredkschott.com/post/2014/02/conquering-asynchronous-context-with-cls/
- Async Listeners
  - https://github.com/othiym23/async-listener
  - https://github.com/joyent/node/pull/6011
  - https://github.com/joyent/node/blob/master/doc/api/process.markdown#async-listeners

**Comment by othiym23** [comment]
+1, although I think it would be most interesting to talk about asyncListeners and the new event listener stuff that @trevnorris is hacking on, with CLS being an application of the API(s). Also, it would be cool to get @dazld to talk a little about his experiences with CLS as an end user.

**Comment by dshaw** [comment]
Sounds great. @dazld, what do you think? You interested in coming on @NodeUp?

**Comment by creationix** [comment]
sounds like fun

**Comment by trevnorris** [comment]
As long as it's after Node Summit, I'm cool with it. :)

**Comment by dazld** [comment]
hey guys! sure, would love to!

**Comment by dazld** [comment]
We're using cls for this kind of stuff:
- Abstraction of values that might be 'global' in a browser context (things like cookies, auth tokens)
- Maintaining per-request state in a serving http context
- Cleanly avoid passing around tons of objects to everything, attaching things to `req` etc
- being able to use event listeners and know they are doing the right thing (especially WRT below..)
- Means we can have an async page rendering process on the server, especially useful in context of writing non-blocking async code, and being lazy with knowing what data we may or may not need to serve a request

**Comment by dshaw** [comment]
@dazld Excellent! Glad to have you on board.

**Comment by dshaw** [comment]
@nodeup @floating @othiym23‎ @trevnorris @creationix @dazld 

Pencilled this in for Thursday 12/19. What do you all think?

**Comment by trevnorris** [comment]
@dshaw I'll be visiting family from 19-27 and won't be available during that time.

**Comment by creationix** [comment]
It's good for me.

**Comment by dshaw** [comment]
Having @trevnorris on this show is key, so let's look to reschedule. Next dates on my NodeUp calendar are: 1/2 and 1/16.

**Comment by trevnorris** [comment]
@dshaw Right now either of those dates work for me.

**Comment by othiym23** [comment]
I'm fine for either 1/2 or 1/16!

**Comment by dazld** [comment]
Both dates in Jan are good for me too.

**Comment by AndreasMadsen** [comment]
Just letting you know that [`trace`](https://github.com/AndreasMadsen/trace) is now another application for `AsyncListener`.

**Comment by FredKSchott** [comment]
@dshaw @othiym23 Did this show ever happen? +1 if not, I'd love to see a show about CLS and the current state of AsyncListener. I'm sure it would blow a lot of peoples minds (I know it did for me :)

If you need more people, I'd be happy to share my experiences building our logging framework on top of it (see: http://fredkschott.com/post/2014/02/conquering-asynchronous-context-with-cls/)

**Comment by dshaw** [comment]
@FredKSchott Dope.

We're currently waiting on @trevnorris to come back from paternity leave. Should be soon though.

**Comment by othiym23** [comment]
I love the idea of having @FredKSchott on to talk about building a logging framework with asyncListeners / CLS!

**Comment by gabrielf** [comment]
:+1: would listen!

**Comment by floating** [comment]
@trevnorris @creationix @dazld Are you available to record this Thursday (3/27) at 11am PDT? 

// @dshaw @othiym23‎

**Comment by trevnorris** [comment]
Think that time works for me.

**Comment by dshaw** [comment]
@FredKSchott @trevnorris Want to come to New Relic and record live?

**Comment by othiym23** [comment]
I'm available, although we'll need to reschedule a meeting here at NR.

@janaboruta is it OK with you / Thea the other members of the New Relic community team if we use the podcasting studio?

**Comment by janaboruta** [comment]
@othiym23 That's fine with us. I'll ping you on Hipchat to discuss the logistics.

**Comment by dazld** [comment]
Count me in.

**Comment by FredKSchott** [comment]
+1 Count me in as well!

**Comment by dshaw** [comment]
WORDS!! Let's do this.

@othiym23‎ @trevnorris @dazld @FredKSchott Please take a moment to drop an email to nodeup@gmail.com and dshaw@dshaw.com with your Google Docs friendly email, your Skype name and Twitter handle. Thank you!

**Comment by charandas** [comment]
@dshaw will this be broadcasted live in any form?

**Comment by creationix** [comment]
Sorry guys, I'm ultra busy and working 12 hours days this week to catch up.  It would be irresponsible for me to add another hour to my schedule.  On the bright side, @othiym23 knows fairly well my input into the conversation.

I've always wanted an event source hook in node for implementing things like nextTick, domains, long stack traces, etc.  I'm sad that event emitters are considered part of the event system when they are clearly sync constructs and I wish the core APIs were more callback based and less event based to make tracking this stuff easier.  The edge cases are pretty nasty in the current semantics.

Have fun!

**Comment by CrabDude** [comment]
I know this is closed and already recorded (haven't listened to it yet), but for the sake of the argument, AsyncListener is implemented at the wrong end of the stack to properly solve issues like long-stack traces, CLS and/or async try/catch properly without shimming EE to properly set the handler context differently (at time of handler listen, not time of EE construction).

FWIW, https://github.com/CrabDude/trycatch/issues/32

**Comment by dshaw** [comment]
@CrabDude Thanks for connecting the discussion.

**Comment by mgan59** [comment]
:+1:
