### ISSUE TITLE
NodeSchool

### ISSUE THREAD

**Issue by rvagg** [nodeup/contribute#22]
### [NodeUp #55](http://nodeup.com/fiftyfive)

We need to talk about this. London, SF, Dublin, I'll do a Sydney one soon.
- @mikeal
- @maxogden
- @brianloveswords
- @jlord
- @raynos

?

**Comment by mikeal** [comment]
A few notes from our talking afterwards.
- we need a better way for people to signal when they need help, something easy that isn't scary for people. finding people in need is hard and a lot of us ended up in conversations with people in between that we would gladly pause to help someone but nobody was asking for help because they felt they would be interrupting.
- a debugging school would be cool, hand people broken code that they learn to fix.
- RSVP doesn't really mean shit. We let in anyone that showed up even if they didn't sign up but the fact that it "sold out" for a while probably kept some people away when the retention rate was maybe 60 or 70 percent of those that signed up.

**Comment by rvagg** [comment]
on that last point I was considering a $5 charge for one in Sydney just to make people take RSVP more seriously.

Also, this thread has lots of notes: https://github.com/nodeschool/discussions/issues/73

**Comment by mikeal** [comment]
yeah, it depends on if you think you'll actually max out the capacity of the venue you're doing it in.

**Comment by Raynos** [comment]
Some things I noted
- Being a mentor is hard. I did a reasonable job of asking people how they were doing but some people took multiple prods to admit they were stuck. Having some kind of way for people to easily ask for help would be nice. This is a general mentoring / teaching problem.
- our event being sold out did keep people I knew away. Not sure how to manage capacity.

Some things that were cool
- The ratio of male/female and advanced/begginner was good. I was impressed with both the number of females and the number of beginners.
- Most people I talked to had positive things to say about the workshop and enjoyed it.

**Comment by brianloveswords** [comment]
Awesome, thanks for kicking this off @rvagg! I'm trying to plan a Brooklyn one for early/mid December.
- I'm definitely +1 on a token donation – we did this for BrooklynJS and it seriously cut back on the amount of attendee absenteeism (IIRC, we sold 78 tickets and only 5 no-shows).
  - My one slight concern is that it might deter people who want to learn but are strapped for cash. I've been trying to think about ways to get around that, maybe $5 with some limited free slots that require an application letter? That way there's still some effort involved and people won't just sign up to sign up. IDK, worth thinking about.
- Debugging school sounds rad.

**Comment by mikeal** [comment]
The capacity planning is easily solvable in two ways.
- Get a venue big enough to absorb the max you think will actually show up. I think Heroku's venue would have fit as many people as would have signed up if we would have kept tickets open indefinitely and sold to well over their capacity.
- Create some kind of commitment guarantee, like charging money, even if it's $1.

TBH, San Francisco is probably worse about this than most other cities. Max did the exact same thing in London and has a much better retention rate.

**Comment by max-mapper** [comment]
I wanted to open up more tickets but Heroku wasnt comfortable above 140 as they hadn't run a meetup that large in their space yet. We had about 100 people show up, so 30-40 no shows. In London we had 10-20 no shows.

**Comment by jlord** [comment]
At the SF/Heroku meet up another mentor and I were discussing how asking questions could be made better. Something that reduced any fear about asking questions, made the question-asker feel less in the spotlight and removed the need for the asker to hold a hand up and wait until they've had eye contact with a mentor. 

So maybe some type of flag that can be raised (thinking about those little realtime conf flags)? But it could also be as simple as a two sided and two colored something (plate? cup?) that can be handed out to groups/tables to be flipped when someone has a question.

**Comment by Raynos** [comment]
@jlord I think two sided [beverage coasters](http://en.wikipedia.org/wiki/Beverage_coaster) would be rad.

**Comment by mikeal** [comment]
anything that is on a table will be covered too often.

maybe some kind of sign that can be attached to your laptop and flipped at will. then you can make _everyone_ have the sign on and just flip it when they need help. if they have to go grab it only when they need help i think they'll be less likely to do so.

**Comment by jordangarcia** [comment]
I think it would've been nice to have more people doing the same lessons sitting near each other.  It would better encourage discussion amongst groups of people on how to tackle the problems at hand.

**Comment by parshap** [comment]
Some general feedback from attending the SF event as a mentor:

At Heroku, the "amphitheater" area didn't work too well in my experience. At least not with that many people there. No one seemed to want to ask for help and it was hard to climb over people just to see if they needed help.

@mikeal:

> maybe some kind of sign that can be attached to your laptop and flipped at will. then you can make everyone have the sign on and just flip it when they need help. if they have to go grab it only when they need help i think they'll be less likely to do so.

I don't think flipping a visible-to-everyone sign on your laptop to indicate you need help will be much less social anxiety than raising your hand.

@jordangarcia:

> I think it would've been nice to have more people doing the same lessons sitting near each other. It would better encourage discussion amongst groups of people on how to tackle the problems at hand.

:+1: Letting students try and help each other (maybe with mentor supervision) sounds like a great idea!

**Comment by olizilla** [comment]
Yep, at the London event it seemed like people were more willing to ask
questions of the people sat next to them rather than summon a mentor, or
admit they were stuck as the mentors did the rounds.

Smaller tables of ~8 people with 1 mentor per table could work well if you
can find that many mentors. I'm assuming that the entry requirement for a
mentor is enthusiasm and having completed the workshoppers, so as node
school rolls on, the pool of potential mentors will grow.

In lieu of 1 mentor per table, just mixing up people and ability levels
would help. NodeConf did that really well.

On Mon, Nov 25, 2013 at 5:55 AM, Parsha Pourkhomami <
notifications@github.com> wrote:

> At Heroku, the "amphitheater" area didn't work too well in my experience.
> At least not with that many people there. No one seemed to want to ask for
> help and it was hard to climb over people just to see if they needed help.
> 
> @mikeal https://github.com/mikeal:
> 
> maybe some kind of sign that can be attached to your laptop and flipped at
> will. then you can make everyone have the sign on and just flip it when
> they need help. if they have to go grab it only when they need help i think
> they'll be less likely to do so.
> 
> I don't think flipping a visible-to-everyone sign on your laptop to
> indicate you need help will be much less social anxiety than raising your
> hand.
> 
> @jordangarcia https://github.com/jordangarcia:
> 
> I think it would've been nice to have more people doing the same lessons
> sitting near each other. It would better encourage discussion amongst
> groups of people on how to tackle the problems at hand.
> 
> [image: :+1:] Letting students try and help each other (maybe with mentor
> supervision) sounds like a great idea!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/22#issuecomment-29179350
> .

## 

Oli Evans
http://oli.zilla.org.uk

**Comment by mikeal** [comment]
I can make time this week, I'm going to be cooking for like 3 days but I can schedule around it.

**Comment by dshaw** [comment]
@mikeal Great. @floating will get everybody scheduled up.

@maxogden @brianloveswords @jlord @olizilla and/or @Raynos. Can you be on this week? The streams max out at 5, but maybe Max and Jessica can be on together.

**Comment by Raynos** [comment]
Oh this is a nodeup thread. I can be on nodeup this week.

**Comment by dshaw** [comment]
;-) Yep. I didn't want to interrupt the constructive discussion that was happening, but yes this is a NodeUp thread.

**Comment by brianloveswords** [comment]
hahaha I totally didn't realize this was a nodeup thread. I can try to make time!

**Comment by floating** [comment]
@brianloveswords @jlord @olizilla @Raynos Hey all, sorry I had already been scheduling this. Mikeal, Max and Rod are set for this Friday at 1pm PT and we have one more spot. Reply here if you can make it at that time, whoever we hear back from first will get added. (sorry we overbooked this one a little bit)

**Comment by rvagg** [comment]
if none of you can make it then @timoxley is a good candidate, author of the functional-javascript, runs a small group that does these workshops in Singapore, organiser of CampJS where we ran the initial learnyounode with ~80 students and ~10 supervisors (including Tim of course).

**Comment by Raynos** [comment]
I can make it but you should probably have someone running one of the not SF meetups fill in the last spot like @brianloveswords @olizilla of @timoxley

**Comment by timoxley** [comment]
Dang, I'll still be in the air travelling back to Australia at this time.

**Comment by jlord** [comment]
@maxogden and I are together in Middle Georgia (woot!) so I can join but I that won't take up another spot, I don't think

**Comment by floating** [comment]
@jlord Awesome :) yeah that doesn't take up a spot so we still have one open.

**Comment by olizilla** [comment]
I'm pretty sure @brianloveswords said he was working on adding in [OpenBadges](http://openbadges.org/) magic to NodeSchool. Right now when you complete a workshopper, you have the warm glow of the terminal to show for your efforts... but people love badges. Just look at the laptop sticker fetish. Getting a badge for completing a workshopper would be a really nice addition.

I've corralled the mentors from @maxogden & @jlord's inaugural London NodeSchool (which was awesome!) to be on hand before LNUG events, so we can run mini NodeSchools each month to help the stuck.

Given the choice, I'd rather hear about MOAR BADGES, than mini NodeSchools. Go on @brianloveswords, you know you want to.

**Comment by brianloveswords** [comment]
@floating hey, I'm back at my parents for Thanksgiving and the internet is ridiculously spotty. I can try to be on tomorrow at 4:00pm EST (right?) but my connection might drop (or it might be perfect). Unless someone else wants to give it a shot, I'll try to be there!

**Comment by floating** [comment]
@brianloveswords Ok awesome, let's try.
