### ISSUE TITLE
NodeUp Teams: WalmartLabs and #nodebf

### ISSUE THREAD

**Issue by rvagg** [nodeup/contribute#23]
### [NodeUp #56](http://nodeup.com/fiftysix)

With:
- @dshaw
- @hueniverse
- @nvcexploder
- @kpdecker
- @wpreul

Topics:
- Node **_at scale**_
- Walmart tech stack.
- Tools.
- Modules used.
- Open source.
- Node.js pain points.
- What works, what doesn't.

**Comment by nizaroni** [comment]
I loved the openness of the whole `#nodebf` event, especially considering how critical a time such as Black Friday can be for a production system. Would be cool to hear the story behind the decision to be so forthcoming. Also, would be neat to hear about the predicted vs. actual traffic and how a team's preparation might change when a spike in traffic is a virtual certainty.
