### ISSUE TITLE
Nodeup.com redesign concept & RFC

### ISSUE THREAD

**Issue by bmathews** [nodeup/contribute#24]
This is an unsolicited redesign of nodeup.com and a request for comments.

Purposes of design/development work would be for:
- Modernization
- Improve responsiveness
- SEO improvements

![nodeup-redesign](https://f.cloud.github.com/assets/848347/1699860/a42d8948-5fcc-11e3-9a66-874d98a28166.png)
[Full Size](https://f.cloud.github.com/assets/848347/1699860/a42d8948-5fcc-11e3-9a66-874d98a28166.png)

**Comment by floating** [comment]
Hey @moonsspoon, thanks for mocking this up. Though I fully agree the design of the site is in need of an update I think this is something we're going to push to the new version. The functionality of the new site will be different than the current one and we should design around that. A repo for the new site should be up soon and welcoming contributions.

**Comment by bmathews** [comment]
@floating Glad to hear it's in motion! Looking forward to the growth of NodeUp.

**Comment by bmathews** [comment]
Any updates on the new website @floating?

**Comment by bmathews** [comment]
(srsly dying over here trying to find a stream on the mobile site)

**Comment by bmathews** [comment]
(and if there's anything we can do to help, let us knoww!)

**Comment by dshaw** [comment]
:+1:
