### ISSUE TITLE
NodeUp: A Continuous Docker Show

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#25]
### [NodeUp #57](http://nodeup.com/fiftyseven)

The concept for this show might a  might be a bit too tightly scoped with Continuous-\* + Docker, but I think there's significant enough activity and interest in this area to have a really great show.

With:
- @dshaw
- @niallo‎
- @mbrevoort‎
- @dscape 
- @jacobgroundwater

Topics:
- Continuous deployment and testing with docker

**Comment by max-mapper** [comment]
I think @jacobgroundwater would be good mostly because I think NodeOS would be awesome with first class docker support and a super awesome node deployment solution

**Comment by dshaw** [comment]
@maxogden Nice one! Thanks. I leave it to @jacobgroundwater to say how close @nodeos is to primetime.

**Comment by dscape** [comment]
+1

Cool to be back :) Looking forward to it @dshaw @floating :+1:

**Comment by groundwater** [comment]
Hey guys, I'd be happy to chime in about my experiences using Docker to work on NodeOS. The project is, and has for a while, been in a runnable state on Docker. I can't really speak to completeness beyond that, people's imaginations grow quickly about this project.

Feel free to ask me more details here, you can decide if it's gonna fit with the shows theme.

**Comment by floating** [comment]
@dshaw @niallo‎ @mbrevoort‎ @dscape @jacobgroundwater Any chance all of you are available to record this show on the 2nd?

**Comment by dscape** [comment]
LGTM

**Comment by niallo** [comment]
I'm on vacation in Mexico till January 11th -with sketchy wifi till then.

On Monday, December 30, 2013, Nuno Job wrote:

> LGTM
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/25#issuecomment-31365649
> .

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by groundwater** [comment]
I'm around; If you need to pick another time I'm in Portland from the 6-12, but I'll have wifi.

**Comment by dshaw** [comment]
@niallo I'd really like to have you on this show. Is there any chance you could find a location with slightly better than normal wifi for a few hours?

**Comment by mbrevoort** [comment]
It depends on the time. What time are you thinking?

**Comment by niallo** [comment]
@dshaw would love to be on the show. It's a bit tricky but I'm trying to
arrange use of a well-connected office for a few hours on jan 3rd or 4th.

Let me get back to you to confirm but hopefully I can secure that for the
podcast.

On Monday, December 30, 2013, Daniel Shaw wrote:

> @niallo https://github.com/niallo I'd really like to have you on this
> show. Is there any chance you could find a location with slightly better
> than normal wifi for a few hours?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/25#issuecomment-31374276
> .

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by floating** [comment]
@mbrevoort we're going to record at 11am pacific /@dshaw @niallo‎ @dscape @jacobgroundwater

**Comment by mbrevoort** [comment]
Ok, i can make that.

**Comment by groundwater** [comment]
+1

**Comment by dscape** [comment]
In the calendar :)

**Comment by floating** [comment]
@niallo Were you able to arrange anything for today? We're planning to record at 11am pacific.

**Comment by niallo** [comment]
Definitely can't record today I'm afraid. In transit.

On Thursday, January 2, 2014, C. Jordan Muir wrote:

> @niallo https://github.com/niallo Were you able to arrange anything for
> today? We're planning to record at 11am pacific.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/25#issuecomment-31458867
> .

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by mbrevoort** [comment]
Should we reschedule? I'd rather have a richer conversation than rush it.

**Comment by floating** [comment]
@mbrevoort @dshaw @dscape @jacobgroundwater Yeah, I think we're going to reschedule.

@niallo‎ When are you available next?

**Comment by groundwater** [comment]
Find by me, I wouldn't mind preparing some demos people can try out after the show.

**Comment by floating** [comment]
@niallo‎ @mbrevoort‎ @dscape @jacobgroundwater Any chance you're all are available to record this show on Friday the 10th around 2pm pacific?

**Comment by groundwater** [comment]
all of friday works for me

**Comment by niallo** [comment]
I'll be in Mexico City. I'll hopefully have decent wifi there that day.
Fingers crossed :) connectivity is sketchy here.

Alternatively if you guys can wait till Monday, I'll be home and will have
a stable connection for sure.

On Monday, January 6, 2014, Jacob Groundwater wrote:

> all of friday works for me
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/25#issuecomment-31699247
> .

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by dscape** [comment]
yup

**Comment by groundwater** [comment]
Monday/Friday both work

**Comment by dshaw** [comment]
Monday is not an option for me. I could potentially try to fit this in **next** Thursday after #19 Node Teams: Groupon at 11am and before the NodeBots SF meetup at 5pm. That's pretty insane, especially since I'll be coming off 3 straight days of conducting training. I will need to find a cave to hide in to recover from all that extroverting. However, if we're uncertain about doing the 10th, that's what I'd like to do.

**Comment by niallo** [comment]
Got to my accommodation in Mexico City. Wifi seems pretty decent here but I
still need to test real time audio. You use skype or something else for the
podcast? I'll try it out in advance of Friday to make sure the connection
is up to wideband audio.

On Tuesday, January 7, 2014, Daniel Shaw wrote:

> Monday is not an option for me. I could potentially try to fit this in
> _next_ Thursday after #19 https://github.com/nodeup/contribute/issues/19Node Teams: Groupon at 11am and before the NodeBots SF meetup at 5pm.
> That's pretty insane, especially since I'll be coming off 3 straight days
> of conducting training. I will need to find a cave to hide in to recover
> from all that extroverting. However, if we're uncertain about doing the
> 10th, that's what I'd like to do.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/25#issuecomment-31790421
> .

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by floating** [comment]
@niallo yep we use skype, let us know how it goes

**Comment by floating** [comment]
Is this a go for tomorrow? (at 2pm pacific)

@mbrevoort‎ Are you available? 

@niallo‎ Is your connection good enough? 

 // @dshaw @dscape @jacobgroundwater

**Comment by dshaw** [comment]
:+1: for me

**Comment by groundwater** [comment]
Red leader, standing by

**Comment by niallo** [comment]
I tested Skype last night and it was fine. Hopefully be up to the task
tomorrow afternoon. I'll be on Skype - I'm "nialljohiggins" btw.

On Thursday, January 9, 2014, Jacob Groundwater wrote:

> Red leader, standing by
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/25#issuecomment-31982730
> .

## 

Niall O'Higgins
W: http://niallohiggins.com
E: n@niallo.me
T: @niallohiggins

**Comment by dscape** [comment]
tomorrow is today right? :)

**Comment by dshaw** [comment]
@mbrevoort You in? http://m.wolframalpha.com/input/?i=+Jan+10+2014+2%3A00pm+PT

**Comment by mbrevoort** [comment]
I have a conflict that I should be able to bump by an hour; so I'm in for
an hour!

**Comment by dshaw** [comment]
Sounds good. :balloon:

**Comment by jimkang** [comment]
Question for the panel: As a guy that's only played with Docker for a few days trying to set up a dev stack VM, it seemed to me that the series of image diffs used by Docker were not very transparent, compared to, say, lines of text in a shell script. I kept wishing there was a way to convert images back into Dockerfiles. How do you square this? Or am I thinking of this the wrong way?
