### ISSUE TITLE
Distribute podcast with BitTorrent

### ISSUE THREAD

**Issue by astro** [nodeup/contribute#3]
This is an invitation. node is open source, Bitlove.org is free software, perfect fit!

**Comment by dshaw** [comment]
Cool. If @floating wants to set this up, I think it's great.

**Comment by dshaw** [comment]
I've heard that the file is especially slow to download in Europe, mostly heard this from Germany. @janl and others. I'd still like to move to SoundCloud because it open things up for inline comments. I think that would be fun.

**Comment by dshaw** [comment]
Done. It's seeding now.

**Comment by dshaw** [comment]
http://bitlove.org/nodeup/nodeup
