### ISSUE TITLE
NodeUp: an npm show

### ISSUE THREAD

**Issue by indexzero** [nodeup/contribute#32]
Moving @floating discussion from email to Github. @janl and myself are confirmed for _Thursday, 2/6/14, 11am PT (UTC-8)._

Looking for responses from @dshaw @isaacs @seldo.

**Comment by indexzero** [comment]
So turns out Thursday did not work for @isaacs, or @janl. Schedule roll call. I'm free Feb 9, 10, 11, 12, and 14.

**Comment by janl** [comment]
Of these I can only do 9th and 10th. 9th preferred.
