### ISSUE TITLE
A JavaScript BitTorrent show

### ISSUE THREAD

**Issue by rvagg** [nodeup/contribute#38]
WIth @feross and @mafintosh, perhaps @deoxxa is still interested in this area too

**Comment by eugeneware** [comment]
:+1:

On Mon, May 12, 2014 at 2:46 PM, Rod Vagg notifications@github.com wrote:

> WIth @feross https://github.com/feross and @mafintoshhttps://github.com/mafintosh,
> perhaps @deoxxa https://github.com/deoxxa is still interested in this
> area too
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nodeup/contribute/issues/38
> .

## 

_Eugene Ware_
Chief Executive Officer

Phone: +61 3 9955 7041
Email: eugene@noblesamurai.com
Twitter: @EugeneWare http://twitter.com/EugeneWare

_Noble Samurai Pty Ltd_
Level 1, 234 Whitehorse Rd
Nunawading, Victoria, 3131, Australia

noblesamurai.com http://www.noblesamurai.com/ | eugeneware.com |
facebook.com/Eugene.S.Ware http://www.facebook.com/Eugene.S.Ware

**Comment by feross** [comment]
So down!

**Comment by feross** [comment]
We should also have @astro on there!

**Comment by dshaw** [comment]
Sounds great.

**Comment by mafintosh** [comment]
Sounds awesome. I'm down

**Comment by dshaw** [comment]
@feross @mafintosh @deoxxa @astro Want to do this on Saturday, May 22nd at 10:30am PT?

**Comment by mafintosh** [comment]
Saturday is not the best day for me (I'm roaming around Oslo with no internet).
I'm back in Copenhagen Sunday 14:00 UTC though and any time after that fits me well.

I might be able to find a decent internet hotspot though if Saturday fits everyone else :)

**Comment by astro** [comment]
11am PST (20pm CEST) is the earliest possible time for me.

**Comment by deoxxa** [comment]
I think this is going to be right in the middle of preparations for CampJS,
of which I've somehow become a part, so I won't be able to make it.

**Comment by dshaw** [comment]
Gah. OK. @feross @mafintosh @deoxxa @astro it looks like this Saturday's going to be a no go. I'm going to be at JSConf next week so I'm going to have to come back with an alternate date.

@deoxxa Happy CampJS!

@mafintosh Congrats on a great talk at Web Rebels. We'll get on soon. Safe travels.

**Comment by mafintosh** [comment]
@dshaw Thanks! In general I'm pretty flexible timewise. Looking forward to this nodeup!

**Comment by feross** [comment]
@dshaw sounds good. looking forward!

**Comment by daviddias** [comment]
What about extending it to P2P in the browser and all the WebRTC goodness? :)

**Comment by astro** [comment]
did http://bitlove.org/nodeup/nodeup get a mention?

**Comment by feross** [comment]
@astro no, that particular url didn't get a mention. i didn't even know about it! but, we did mention you as someone to follow on twitter for people interested in p2p!
