### ISSUE TITLE
NodeUp: Breach

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#43]
### NodeUp #?

With:
- @dshaw
- @spolu
- @alevizio
- @guille
- @goldwater 

Topics:
- Breach - A browser for the HTML5 era
  - http://breach.cc/
  - https://github.com/breach/breach_core

**Comment by spolu** [comment]
Awesome. @guille and @alevizio should be OK for it as well.

**Comment by dshaw** [comment]
Great. Glad to hear that!

**Comment by groundwater** [comment]
~~:thumbsdown: I'm down~~ sorry I can't make it

**Comment by FredKSchott** [comment]
+1 This sounds rad, looking forward to hearing it
