### ISSUE TITLE
A content platform show

### ISSUE THREAD

**Issue by rvagg** [nodeup/contribute#44]
- KeystoneJS - @jedwatson - http://keystonejs.com/
- DocPad - @balupton - http://docpad.org/
- Ghost - @ErisDS - https://ghost.org/

Roughly in the area of CMS / blogging / site generation

**Comment by balupton** [comment]
Woot woot.

**Comment by JedWatson** [comment]
Sounds great, would love to join in.

**Comment by davidkaneda** [comment]
Hey hey :) @davidkaneda - http://buckets.io

**Comment by rvagg** [comment]
@dshaw this issue can be closed

**Comment by balupton** [comment]
nodeup.com/seventynine
