### ISSUE TITLE
An npm client update show

### ISSUE THREAD

**Issue by rvagg** [nodeup/contribute#45]
@timoxley and @othiym23

and that's about it I reckon

**Comment by othiym23** [comment]
Topics:
- extensibility through API extraction vs additional lifecycle hooks
- finding the right coupling and cohesion balance for various npm components (and how that process is inevitably iterative / accordion-like)
- using this to lay the groundwork for an explicit architecture for the npm CLI
- documenting and / or specifying the registry API
- and using that as a way to make the code base more accessible to a wider contributor base

Also it might be fun to talk about how much functionality it makes sense to put in the CLI itself versus providing tools for forks and "superclients" (like `apm`, `jspm`, `yapm`, and Yeoman generators) to specialize npm behavior for specific use cases.

I bet @domenic has opinions about this stuff too!

**Comment by rvagg** [comment]
@othiym23 do you have a rough target date for 2.0.0? It'd be good to time this approximately with that release.

**Comment by othiym23** [comment]
@rvagg Not a date, but the main blocker for the release of 2.0.0 is updating the cache to properly deal with pulling packages from multiple registries. Right now this is contingent on me extracting the cache functionality into `npm-cache`, which feels like it's probably a few weeks' work with no distractions. "With no distractions" is the challenging part of that last sentence. ;)

**Comment by timoxley** [comment]
@othiym23 @floating @domenic cc @rvagg 

Is everyone ok to do this this week? The times below seem most reasonable. We typically record on Tuesdays but I'm flexible with date and time. 

[![image](https://cloud.githubusercontent.com/assets/43438/3794023/accc73d0-1ba5-11e4-8422-85a5db2d018b.png)
![image](https://cloud.githubusercontent.com/assets/43438/3794062/6f1c4e88-1ba6-11e4-9b69-d654e97d875c.png)
![image](https://cloud.githubusercontent.com/assets/43438/3794038/215121ce-1ba6-11e4-9fee-36b077b21dc1.png)](http://www.timeanddate.com/worldclock/meetingtime.html?day=5&month=8&year=2014&p1=236&p2=224&p3=179&iv=1800)

My preferred/suggested time is probably: 
![image](https://cloud.githubusercontent.com/assets/43438/3794072/b3cb588a-1ba6-11e4-9b95-78fc2b967525.png)

**Comment by timoxley** [comment]
edit: added @domenic

**Comment by domenic** [comment]
Any of the times that are NYC evening (including @timoxley's preferred time) work well for me.

**Comment by othiym23** [comment]
@timoxley's preferred time works well for me! As do most of the others!

**Comment by timoxley** [comment]
your call @floating

**Comment by floating** [comment]
@timoxley's preferred time works! I will send out a doc.

**Comment by timoxley** [comment]
@domenic @othiym23 I've updated the doc with some topics, I feel like we should use this opportunity to do some PSAs, since a big problem for npm is that people just don't know features exist or how to use them but this may be obvious/boring for people as it's the same material we've been talking about for the last few months – I'm happy to move on to new topics, feel free to get in there and change it up entirely.
