### ISSUE TITLE
NodeUp Live at JSFest Oakland

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#46]
I would love suggestions for a theme. The framework debate show was awesome... though tragically ephemeral since we couldn't record it.

This time we'll be in <strike>Emeryville</strike>Oakland. Let's have some fun.

What topic should we cover and who should we have on the panel?

**Comment by rvagg** [comment]
@mikeal is this scheduled? Want to provide input here?

**Comment by rvagg** [comment]
@dshaw this issue can be closed

**Comment by dshaw** [comment]
@rvagg Added you as admin. Thank you.
