### ISSUE TITLE
Developer mental health episode

### ISSUE THREAD

**Issue by rvagg** [nodeup/contribute#49]
Would love to have a show on this topic, perhaps keeping it shorter than usual to optimise for maximum listenership.

My initial suggestions for guests are:
- @funkatron who apparently did a great talk at Nodevember, I don't know the specifics but I heard great feedback on it
- @GregBaugues who, while not active with Node, does a lot of speaking on this topic and I imagine could at least point us towards other speakers if he's not up for it.
- @aredridel has also expressed a lot of interest in this area

Not sure of exactly a show structure would be, open to suggestions of course!

**Comment by dshaw** [comment]
+1000 yes!

**Comment by funkatron** [comment]
I'm happy to do this. You can see a video of my talk from Nodevember here if you like: http://funkatron.com/osmi

**Comment by aredridel** [comment]
I would be so into this. Both personal experience and those around me. Doubly so talking about the experiences minority voices have in tech, and the stresses that show up there.

**Comment by aredridel** [comment]
And @funkatron's talk was amazing.

**Comment by GregBaugues** [comment]
I'd be honored (and a goal of 2015 is to start doing more in Node so this
is a great kick in the pants).

How may I be of service to make this happen?

**Comment by rvagg** [comment]
OK, perhaps the path to making this happening _sooner_ rather than later is to outline some sections, then we can just drop that into a show doc and get rolling.

The format is normally 3 distinct show sections, separated by 3 sponsor spots, aiming for ~20 minutes per section but I personally think we'd be doing ourselves a disservice to let this go on too long because it'll make it more _skippable_ in the list of podcasts that people choose to listen to.

So, can we brainstorm 3 distinct show sections that follow-on from each other? Ideally the section headings are broad enough to allow for interesting discussion amongst the group but focused enough to allow for mapping in some discussion points to the doc so it doesn't get too stale and the host can lead it on if need be.

I'm hesitant to propose sections myself so will let one of you to start the process!

**Comment by aredridel** [comment]
- Self care
- Recognizing distress
- Resources
- Asking for help
- stigma
- Community and its effects
- How marginalized people take the brunt of some things

**Comment by rvagg** [comment]
Just talking to @floating about this one and we're agreeing that:
- Aim for ~30 mins total talk time
- Leave the sponsor read spots out of the middle of this so it can be a continual conversation
- Aim for getting it out by the end of the year

Working on @aredridel's list, here's my suggestion for a flow (doesn't need to be rigid):
- Introductions, backgrounds and expertise and any required disclaimers re professional advice
- Defining the topic of discussion, what are the various spectrums we are talking about
- Prevalence, in general and in our industry specifically (last time I researched this the numbers suggested that incidence rates of mental illness in STEM weren't higher than the general population but that doesn't match with anecdotal evidence, does anybody have good numbers?)
- Stigma, general community and within our industry
- Community and its effects
- Recognizing symptoms in yourself
- Recognizing symptoms in others
- Self care
- Asking for help
- Resources

Someone want to iterate on that?

**Comment by rvagg** [comment]
I'd like to try and schedule this for next week some time, the panel so far looks pretty good and is in the US, except I'm in Australia and I'm supposed to be on holiday next week so pinning down a time might be tricky. @floating can you try and organise some time suggestions and I'll see if I can make it? Otherwise I'm sure @dshaw can just take this one.

**Comment by aredridel** [comment]
Sounds good; I'm busy until Wednesday, but free after.

**Comment by floating** [comment]
Do either of these work?

Option 1:
 Wednesday(12/17)  @ 2pm  (San Francisco)
 Wednesday(12/17) @ 5pm  (New York)
 Wednesday(12/17) @ 10pm (GMT)
 Thursday(12/18) @ 9am  (Sydney)

Option 2:
  Thursday(12/18) @ 2pm  (San Francisco)
  Thursday(12/18) @ 5pm  (New York)
  Thursday(12/18) @ 10pm (GMT)
  Friday(12/19) @ 9am  (Sydney)

**Comment by rvagg** [comment]
I can make either work I think.

**Comment by aredridel** [comment]
Works for me. I'll grab a quiet room at work.

**Comment by GregBaugues** [comment]
Either works for me as well.

**Comment by funkatron** [comment]
I think I can do either one. Would need it nailed down soon to make plans.

**Comment by floating** [comment]
Let's do Option 2.

**Comment by floating** [comment]
Just shared the doc with everyone, add your thoughts and we can organize them before the show.

**Comment by rvagg** [comment]
@floating I hope you don't mind but I'd like to try something a bit different. I've made the doc commentable by anybody with the link.

Here's the show notes for anybody interested in adding suggestions before we start recording: https://docs.google.com/document/d/1Ucm0Jgl2fbtM7yJ359UxU83zpxdvDl4znLwJMiXdEy0

**Comment by jfhbrook** [comment]
Discuss causes and symptoms. Aim for variety. There are many manifestations of mental illness besides anxiety and depression, and not all of them are caused by overworking (which can be treated with vacation time).

Stigma is important. It's not just a matter of "don't be embarrassed," it can potentially have serious repercussions in both friendships and professional life---not just from admitting a problem but also from (inadvertently) acting out on it. It's not only a matter of acceptance, but possibly one of damage control.

**Comment by eugeneware** [comment]
As most developers tend to be left-brained and fact-oriented, I've found that the scientific research around causes and the effectiveness of different treatments from the Department of Psychology, KU very useful and very practical to treat depression.

The highlights are in this TED video: https://www.youtube.com/watch?v=drv3BP0Fdi8

And the specific recommendations summarised on this page: http://psych.ku.edu/tlc/Elements.html

More details at: http://psych.ku.edu/tlc/

[This book](http://www.amazon.com/Depression-Cure-6-Step-Program-without-ebook/dp/B0097DHV94/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1418787998&sr=1-1&keywords=depression+cure) goes into much more detail and have found it very practical and useful.

Fun facts: A study of results released under the Freedom of Information Act from the FDA showed that "for the results of every drug-company study submitted over a thirteen-year period (1987- 1999) for six commonly used antidepressant medications: Zoloft, Effexor, Prozac, Celexa, Paxil, and Serzone. Incredibly, he found that in 56% of these studies, depressed patients taking an antidepressant drug fared no better than those who took a placebo. Not surprisingly, the drug companies have never published most of these studies.”

Personally, improving my intake of Omega 3s and exercising more often have helped substantially.

Looking forward to this episode guys! Too much stigma around this stuff, particularly around people in remote work environments such as myself.

**Comment by balupton** [comment]
This would be amazing.

Two people in the scene whose talks have impacted me greatly in this area are Brian Brennan:
https://www.youtube.com/watch?v=LlO2_GecWo8

and Jenn Turner:
https://www.youtube.com/watch?v=0_mgp_VWIe0

I also love how people like Isaac Schlueter open up about this too:
http://blog.izs.me/post/87902115343/re-maven-is-like-my-girlfriend

Myself doing my part to:
https://github.com/balupton/website/commit/10c8c4f4924cd8243e3b99f8b3855b752324cee7

**Comment by rvagg** [comment]
@GregBaugues have you been getting the emails btw? You're the only one missing from the details section of the doc so we don't even have your Skype details yet.

**Comment by GregBaugues** [comment]
Hey sorry for the delay. First week back from paternity leave so I'm a bit
behind on things. I'll be back at my desk in two hours. Will update my info
prior to the podcast.

**Comment by GregBaugues** [comment]
When are y'all expecting this podcast to go live?

On Thu, Dec 18, 2014 at 12:03 PM, Greg Baugues greg@baugues.com wrote:

> Hey sorry for the delay. First week back from paternity leave so I'm a bit
> behind on things. I'll be back at my desk in two hours. Will update my info
> prior to the podcast.
> On Dec 18, 2014 5:24 AM, "Rod Vagg" notifications@github.com wrote:
> 
> > @GregBaugues https://github.com/GregBaugues have you been getting the
> > emails btw? You're the only one missing from the details section of the doc
> > so we don't even have your Skype details yet.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/nodeup/contribute/issues/49#issuecomment-67473406.

## 

Greg Baugues
312.952.6796
baugues.com http://www.baugues.com

**Comment by netpoetica** [comment]
Some additional discussion items, if time permits:
- long-term effects of failing to recognize your health slipping away. It's easy to miss the tipping point between occasional detrimental behavior and when that behavior becomes your everyday routine.
- symptoms in open-source vs. workplace. I haven't personally met anyone who has become "mentally ill" (as far as someone as unqualified as myself can allege to perceive) either at work or in open-source, but I have certainly seen erratic behavior and "freak-outs" in both cases that are very different. For example, the "withdraw completely" behavior in the workplace may mean quitting your job, but in open source it may mean deleting 4/5 social media counts or ignoring them. I suppose this could also be "the manifestation of symptoms in different environments"

**Comment by balupton** [comment]
> For example, the "withdraw completely" behavior in the workplace may mean quitting your job, but in open source it may mean deleting 4/5 social media counts or ignoring them

I kind of wrote about this recently: https://medium.com/@balupton/surviving-free-culture-f99b39ceb059

**Comment by egdelwonk** [comment]
Great episode, ya'll. Thanks for putting it together @dshaw.

**Comment by dshaw** [comment]
<3

**Comment by timoxley** [comment]
@rvagg This can be closed :+1:

**Comment by balupton** [comment]
The link to this node up episode is at: http://nodeup.com/eighty

---

Follow up discussions on developer mental health can probably happen on this repo: https://github.com/reignite/burnout.io

**Comment by GregBaugues** [comment]
Are you thinking of devpressed.com?

On Wed, Apr 8, 2015 at 4:49 AM, Benjamin Lupton notifications@github.com
wrote:

> There was a website and repo dedicated to developer mental health, but I
> can't find it. Anyone here aware of it?
> 
> Also found http://baugues.com/depression
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeup/contribute/issues/49#issuecomment-90865636.

## 

Greg Baugues
312.952.6796
baugues.com http://www.baugues.com

**Comment by rhalff** [comment]
I'm thinking about devsuppressed.com to reverse engineer the methods of intelligence agencies.
And define the patterns they use for psychological manipulation.

It doesn't have to result into absolute facts or truth, but could lead to uplifting & insightful graphs.
