### ISSUE TITLE
6to5 show

### ISSUE THREAD

**Issue by timoxley** [nodeup/contribute#50]
6to5 is hot right now.

Let's do a 6to5 show with @sebmck & @zloirock to talk about both 6to5 and corejs purpose, status, the es-next merger, problems, future, lesser known features, etc.

**Comment by sebmck** [comment]
Sounds awesome! ES6 is definently a hot topic right now with the release of io.js and the barrier to entry being heavily reduced.

**Comment by floating** [comment]
http://nodeup.com/eightytwo
