### ISSUE TITLE
NodeUp Teams: Change.org

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#8]
## Friday 7/19 Noon PT

With:
- @sh1mmer
- @ded
- @alif
- @jmerrifield

Topics:
- Change.org tech stack.
- Tools.
- Modules used.
- Open source.
- Control flow. What works?
- JS / CoffeeScript / other?
- Integrating with legacy systems.
- Node.js pain points.

**Comment by ded** [comment]
cc @alif @jmerrifield

**Comment by Oobert** [comment]
This may be were the topic of "open source" is going, but in case it isn't here is a question that still puzzles me.

How do you show/prove/explain that contributing back to open source projects is a good idea? or creating open source projects of common/non-business code is a good idea? It seems that businesses hold their code close with the thought that it is somehow unique to them.

Thank you
Tony

**Comment by zdwolfe** [comment]
I mentioned on Twitter ( https://twitter.com/zdwolfe/status/357301586923491330) but I'll ask here too -  what are the biggest hurdles for corporate adoption of #nodejs? 

Thanks guys, love the podcast.
