### ISSUE TITLE
NodeUp Teams: DIY

### ISSUE THREAD

**Issue by dshaw** [nodeup/contribute#9]
### [NodeUp #49](http://nodeup.com/fortynine)

With:
- @thisandagain
- @drk
- @remixz
- @kaelb

Topics:
- DIY tech stack.
- Do you DIY all of your tech stack? Hah!
- Tools.
- Modules used.
- Open source.
- Control flow. What works?
- JS / CoffeeScript / other?
- Node.js pain points.
- What works, what doesn't.

**Comment by thisandagain** [comment]
I'll be joined by @drk, @zachbruggeman, @kaelb (<-- twitter accounts)

Get ready to have a 15 year old Node.js hacker on NodeUp. :laughing:

**Comment by thisandagain** [comment]
Topic list looks good though we don't integrate with any legacy systems so we could ditch that talking point.

**Comment by remixz** [comment]
Woohoo! :metal: (I am @zachbruggeman btw)

**Comment by kaelb** [comment]
I am also @zachbruggeman

**Comment by kaelb** [comment]
Or am I??

**Comment by remixz** [comment]
@zachbruggeman is all.

![isall](https://f.cloud.github.com/assets/1459603/823702/5ca22aee-f01d-11e2-94fd-9fbc9a2d13cb.jpg)
